routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

// User
Route::group(["prefix" => "user", "as" => "user."], function (){
   Route::get("/mahasiswa-register", "UserController@mahasiswaRegister")->name("mahasiswa.register");
   Route::post("/mahasiswa-register", "UserController@postMahasiswaRegister")->name("post.mahasiswa.register");
   Route::get("/login", "UserController@login")->name("login");
   Route::post("/login", "UserController@postLogin")->name("post.login");
   Route::get("/logout", "UserController@logout")->name("logout");
});

// Admin
Route::group(["prefix" => "admin", "as" => "admin.", "namespace" => "Admin", "middleware" => "admin"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //admin mahasiswa
    Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa."], function (){
        Route::get("/", "MahasiswaController@index")->name("index");
        Route::get("/tambah", "MahasiswaController@tambah")->name("tambah");
        Route::post("/tambah", "MahasiswaController@postTambah")->name("post.tambah");
    });
    //admin dosen
    Route::group(["prefix" => "dosen", "as" => "dosen."], function (){
        Route::get("/", "DosenController@index")->name("index");
        Route::get("/tambah", "DosenController@tambah")->name("tambah");
        Route::post("/tambah", "DosenController@postTambah")->name("post.tambah");
        Route::get("/buat-akun-dosen/{nip}", "DosenController@buatAkunDosen")->name("buat-akun-dosen");
        Route::post("/buat-akun-dosen/{nip}", "DosenController@postBuatAkunDosen")->name("post.buat-akun-dosen");
    });
    //sks
    Route::group(["prefix" => "sks", "as" => "sks."], function (){
        Route::get("/", "SKSController@index")->name("index");
        Route::post("/import-excel", "SKSController@importExcel")->name("post.import.excel");
    });
});

// Mahasiswa
Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa.","namespace" => "Mahasiswa", "middleware" => "mahasiswa"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pembayaran
    Route::group(["prefix" => "pembayaran", "as" => "pembayaran."], function (){
        Route::get("/bayar", "PembayaranController@bayar")->name("bayar");
        Route::post("/bayar", "PembayaranController@postBayar")->name("post.bayar");
    });
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/pengajuan", "PengajuanKPController@pengajuan")->name("pengajuan");
        Route::post("/pengajuan", "PengajuanKPController@postPengajuan")->name("post.pengajuan");
    });
});

// Kaprodi
Route::group(["prefix" => "kaprodi", "as" => "kaprodi.", "namespace" => "Kaprodi"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/detail/{id}", "PengajuanKPController@detail")->name("detail");
        Route::get("/terima/{id}", "PengajuanKPController@terima")->name("terima");
        Route::post("/pilih-dosbing", "PengajuanKPController@pilihDosbing")->name("pilih-dosbing");
    });
});

// Dosen
Route::group(["prefix" => "dosen", "as" => "dosen.", "namespace" => "Dosen"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");

});

app/Models/Kaprodi.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\AdminResetPasswordNotification;

class Kaprodi extends Authenticatable
{
    use Notifiable;

    // declare guard type
    protected $guard = 'kaprodi';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'dosen_id','prodi_id', 'email', 'password',
    ];
    
    public function getCreatedAttribute() 
    {
        return Carbon::parse($this->attribute['created_at'])
                        ->translatedFormat('l, d F Y');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new AdminResetPasswordNotification($token));
    }
}

app/Http/Controllers/Dosen/PengajuanKPController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Service\Impl\SessionServiceImpl;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PengajuanKPController extends Controller
{
    //

}

app/Http/Controllers/Kaprodi/HomeController.php
<?php

namespace App\Http\Controllers\Kaprodi;

use App\Service\Impl\SessionServiceImpl;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    private SessionService $sessionService;

    public function __construct()
    {
        $this->sessionService = new SessionServiceImpl();
    }

    public function dashboard()
    {
        $dosen = $this->sessionService->currentDosen();
        return view("kaprodi.dashboard", [
            "title" => "Dashboard",
            "dosen" => $dosen
        ]);
    }


}

app/Http/Controllers/Kaprodi/PengajuanKPController.php
<?php

namespace App\Http\Controllers\Kaprodi;

use App\Exceptions\PengajuanKPException;
use App\Http\Requests\PengajuanKPPilihDosenRequest;
use App\Model\Dosen;
use App\Model\PengajuanKP;
use App\Service\Impl\PengajuanKPServiceImpl;
use App\Service\Impl\SessionServiceImpl;
use App\Service\PengajuanKPService;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PengajuanKPController extends Controller
{
    private SessionService $sessionService;
    private PengajuanKPService $pengajuanKPService;

    public function __construct()
    {
        $this->sessionService = new SessionServiceImpl();
        $this->pengajuanKPService = new PengajuanKPServiceImpl();
    }

    public function index()
    {

        $nip = $this->sessionService->currentDosen()->nip;

        $pengajuanKp = PengajuanKP::where("nip", $nip)->get();

        return view("kaprodi.pengajuan-kp.index",[
            "title" => "Pengajuan Kerja Praktek ",
            "pengajuanKP" => $pengajuanKp
        ]);
    }

    public function detail(string $id)
    {
        $prodiId = $this->sessionService->currentDosen()->kode_prodi;


        $pengajuanKp =PengajuanKP::find($id);
        $dosen = Dosen::all();
        return view("kaprodi.pengajuan-kp.detail", [
            "title" => "Detail pengajuan KP",
            "pengajuanKp" => $pengajuanKp,
            "dosen" => $dosen
        ]);
    }

    public function terima($id)
    {
        try {
            $this->pengajuanKPService->terima($id);
            return back()->with("success", "Pengajuan diterima");
        }catch (PengajuanKPException $exception){
            return back()->with("error", $exception->getMessage());
        }
    }

    public function pilihDosbing(PengajuanKPPilihDosenRequest $request)
    {

        try {
            $this->pengajuanKPService->pilihDosbing($request);
            return back()->with("success", "Berhasil membilih dosen pembimbing");
        }catch (PengajuanKPException $exception){
            return back()->with("error", $exception->getMessage());
        }
    }
}

app/Http/Controllers/Mahasiswa/PengajuanKPController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Exceptions\PengajuanKPException;
use App\Http\Requests\PengajuanKPRequest;
use App\Model\PengajuanKP;
use App\Service\Impl\PengajuanKPServiceImpl;
use App\Service\Impl\SessionServiceImpl;
use App\Service\PengajuanKPService;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PengajuanKPController extends Controller
{
    //

    private PengajuanKPService $pengajuanKPService;
    private SessionService $sessionService;

    public function __construct()
    {
        $this->pengajuanKPService = new PengajuanKPServiceImpl();
        $this->sessionService = new SessionServiceImpl();
    }


    public function index()
    {
        $pengajuanKP = PengajuanKP::where("nim", $this->sessionService->currentMahasiswa()->nim)
            ->get();

        return view("mahasiswa.pengajuan-kp.index", [
            "title" => "Pengajuan Kerja Praktek",
            "pengajuanKP" => $pengajuanKP
        ]);
    }

    public function pengajuan()
    {
        $mahasiswa = $this->sessionService->currentMahasiswa();
        return view("mahasiswa.pengajuan-kp.pengajuan", [
            "title" => "Form Pengajuan Kerja Praktek",
            "mahasiswa" => $mahasiswa
        ]);
    }

    public function postPengajuan(PengajuanKPRequest $request)
    {
        try {
            $response = $this->pengajuanKPService->pengajuan($request);
            return redirect()->route("mahasiswa.pengajuan.kp.index")->with("success", "Berhasil melakukan pengajuan Kerja Praktek");
        }catch (PengajuanKPException $exception){
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }
    }
}

app/Http/Controllers/PengajuanKPController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Bimbingan;
use App\Dosen;
use App\Mahasiswa;
use App\Pengajuan;
use App\Prodi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
// use Symfony\Component\HttpFoundation\Session\Session;

class PengajuanKPController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('auth:dosen')->except(['formPengajuan', 'kpSubmit', 'status']);
         $this->middleware('auth:web')->only(['formPengajuan', 'kpSubmit', 'status']);
     }

    public function status()
    {
        $id = Auth::user()->mahasiswa_id;
        $data['ditolak'] = Pengajuan::where([
            'mahasiswa_id'=> $id,
            'status' => 'Ditolak'
        ])->get();
        $data['terima'] = Pengajuan::where([
            'mahasiswa_id'=> $id,
            'status' => 'Diterima'
        ])->get();
        
        $id = Auth::user()->mahasiswa_id;
        $data['pengajuans'] = Pengajuan::where('mahasiswa_id', $id)->get();

        return view('pengajuanKP.status', $data);
    }

    public function index()
    {
        $dosenId = Auth::user()->id;

        if (Auth::user()->jabatan == 'kaprodi' OR Auth::user()->jabatan == 'dekan') {
            
            $data['pengajuans'] =  Pengajuan::where([
                ['dosen_id' ,'=', $dosenId],
                ['selesai' ,'=', 0],
                ['status', '=', 'Pengajuan'],
            ])->get();
    
            // dd($pengajuan);
            return view('pengajuanKP.index', $data);
        }else{
            return "Page not found";
        }
        
        
    }
    

    public function formPengajuan()
    {
        $id = Auth::user()->mahasiswa_id;
        $pengajuan = Pengajuan::where('mahasiswa_id', $id)->count();

        $data['pengajuans'] = Pengajuan::where('mahasiswa_id', $id)->get();
 
        $data['ditolak'] = Pengajuan::where([
            'mahasiswa_id'=> $id,
            'status' => 'Ditolak'
        ])->get();
        $data['terima'] = Pengajuan::where([
            'mahasiswa_id'=> $id,
            'status' => 'Diterima'
        ])->get();


        if ($pengajuan == null) {
            return view('pengajuanKP.formPengajuan');
        }else{
            return view('pengajuanKP.status' , $data);
        }
    }

    public function kpSubmit(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required',
            'bidang_pekerjaan' => 'required',
            'deskripsi' => 'required',
            'jml_pegawai' => 'required',
            'kompleksitas_pekerjaan' => 'required',
            'lokasi' => 'required',
            'nm_instansi' => 'required',
            'phone' => 'required',
            'kerangka_pikir' => 'required|mimes:pdf,docs'
        ]);

        // dd($request->file('kerangka_pikir')->getClientOriginalName());
        $nim = Auth::user()->mahasiswa->nim;

        $kerangkaPikir = $this->_uploadFile($nim, $request->file('kerangka_pikir'));

        // dd($kerangkaPikir);

        $mhs = Mahasiswa::where('nim', $nim)->first();
        $kaprodi = Dosen::where([
            'jabatan' => 'kaprodi', 
            'prodi_id'=> $mhs['prodi_id']
            ])->first();

        // dd($kaprodi);
        $kaprodiId = $kaprodi['id'];
        $mahasiswaId = $mhs['id'];
        

        // dd($kaprodiId);
        // dd($request);
        
        $prodi = Prodi::where('id', $mhs['prodi_id'])->first();
        $kdProdi = $prodi['kode_prodi'];

        $date = getdate();

        $year = $date['year'];
        $mon = $date['mon'];
        $back = Pengajuan::count() + 1;




        $noPengajuan = $kdProdi.'KP'.$mon.$year.'00'.$back;

                

        $pengajuan = [
            'dosen_id' => $kaprodiId,
            'mahasiswa_id' => $mahasiswaId,
            'no_pengajuan' => $noPengajuan,
            'judul' => $request->judul,
            'bidang_pekerjaan' => $request->bidang_pekerjaan,
            'deskripsi' => $request->deskripsi,
            'jml_pegawai' => $request->jml_pegawai,
            'jns_pengajuan' => 'KP',
            'kompleksitas_pekerjaan' => $request->kompleksitas_pekerjaan,
            'lokasi' => $request->lokasi,
            'nm_instansi' => $request->nm_instansi,
            'phone' => $request->phone,
            'kerangka_pikir' => $kerangkaPikir,
            'status' => 'Pengajuan',
            'ket' => null,
            'selesai' => 0
        ];

        Pengajuan::create($pengajuan);

        Session::flash('msg', 'Berhasil Ditambah');

        return redirect(route('pengajuanKP.status'));
    }

    private function _uploadFile($nim, $kerangkaPikir)
    {

        $nama = $nim.rand(). '.' . $kerangkaPikir->getClientOriginalExtension();

        $tujuan_upload = 'file_pengajuan/kerangkapikir';

        $kerangkaPikir->move($tujuan_upload, $nama);

        return $nama;

    }

    public function show($id)
    {

        $data['dosens'] = Dosen::all();
        $data['pengajuan'] = Pengajuan::where('id', $id)->first();
        
        return view('pengajuanKP.show', $data);
    }

    public function terima(Request $request, $id)
    {
        $this->validate($request, [
            'dosen_id' => 'required'
        ]);

        $pengajuan = Pengajuan::find($id);
        $pengajuan->status = 'Diterima';
        $pengajuan->save();

        $bimbingan = [
            'kd_bimbingan' => rand(),
            'pengajuan_id' => $request->pengajuan_id,
            'dosen_id' => $request->dosen_id,
            'mahasiswa_id' => $request->mahasiswa_id,
            'bab' => 1,
            'tgl_bimbingan' => null,
            'status' => 'Bimbingan',
        ];

        Bimbingan::create($bimbingan);

        Session::flash('msg', 'Pengajuan Berhasil Diterima');

        return redirect(route('pengajuanKP'));

    }
    public function tolak($id)
    {
        $pengajuan = Pengajuan::find($id);
        $pengajuan->status = 'Ditolak';
        $pengajuan->save();

        Session::flash('msg', 'Pengajuan Berhasil Ditolak');

        return redirect(route('pengajuanKP'));

    }
    public function terimaSyarat(Request $request, $id)
    {
        $this->validate($request, [
            'syarat' => 'required',
            'dosen_id' => 'required'
        ]);


        $pengajuan = Pengajuan::find($id);
        $pengajuan->syarat = $request->syarat;
        $pengajuan->status = 'Terima Syarat';
        $pengajuan->save();


        $bimbingan = [
            'kd_bimbingan' => rand(),
            'pengajuan_id' => $request->pengajuan_id,
            'dosen_id' => $request->dosen_id,
            'mahasiswa_id' => $request->mahasiswa_id,
            'bab' => 1,

            'tgl_bimbingan' => null,
            'status' => 'Bimbingan',
        ];

        Bimbingan::create($bimbingan);



        Session::flash('msg', 'Pengajuan Berhasil Diterima');

        return redirect(route('pengajuanKP'));
    }

}

resources/views/kaprodi/pengajuan-kp/detail.blade.php
@extends('layouts.app')

@section('content')

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br>
            @endforeach
        </div>
    @endif
    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    @if(session('error'))
        <div class="alert alert-success">
            {{ session('error') }}
        </div>
    @endif
    <div class="row mt-3">
        <div class="col-md-7">
            <div class="card shadow-sm mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Detail Instansi KP - {{ $pengajuanKp->judul }}</h6>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <th scope="row">Nama Instansi</th>
                            <td>:</td>
                            <td>{{ $pengajuanKp->nama_instansi }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Lokasi</th>
                            <td>:</td>
                            <td>{{ $pengajuanKp->lokasi }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Alamat Instansi</th>
                            <td>:</td>
                            <td>{{ $pengajuanKp->alamat }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Bidang Pekerjaan</th>
                            <td>:</td>
                            <td>{{ $pengajuanKp->bidang_pekerjaan }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Jumlah Pegawai</th>
                            <td>:</td>
                            <td>{{ $pengajuanKp->jumlah_pegawai }} orang</td>
                        </tr>
                        </tbody>
                    </table>
                    <strong> Deskripsi singkat </strong>
                    <p>{{ $pengajuanKp->deskripsi_pekerjaan }} </p>
                </div>

            </div>
        </div>
        <div class="col-md-5">
            <ol class="list-group list-group-numbered shadow-sm">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="font-weight-bold">Judul</div>
                        {{ $pengajuanKp->judul }}
                    </div>
                    <span class="badge bg-primary rounded-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="font-weight-bold">ID Pengajuan</div>
                        {{ $pengajuanKp->id }}
                    </div>
                    <span class="badge bg-primary rounded-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="font-weight-bold">Tanggal Pengajuan</div>
                        {{ $pengajuanKp->created_at }}
                    </div>
                    <span class="badge bg-primary rounded-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="font-weight-bold">Dosen Pembimbing</div>
                        {{ $pengajuanKp->dosen->nama }}
                    </div>
                    <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
                        Pilih Dosen Pembimbing
                    </button>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="font-weight-bold">Status Pengajuan</div>
                        <span class="badge badge-warning">{{ $pengajuanKp->status }}</span>
                    </div>
                </li>
                @if($pengajuanKp->status == "PENGAJUAN")
                <li class="list-group-item d-flex justify-content-center align-items-start">
                    <a href="{{ route('kaprodi.pengajuan.kp.terima', ["id" => $pengajuanKp->id]) }}" class="btn btn-success rounded-0">Terima Pengajuan</a>
                    <a class="btn btn-outline-danger rounded-0">Tolak</a>
                </li>
                @endif
            </ol>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12">
            <div class="card shadow-sm mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Kerangka Pikir</h6>
                </div>
                <div class="card-body table-responsive">



                    <embed src="{{ asset('storage/kerangka_pikir/'.$pengajuanKp->kerangka_pikir)}}" width="100%" height="800px" />

                </div>
            </div>
        </div>
    </div>



    <!-- Modal -->
    <form method="post" action="{{ route("kaprodi.pengajuan.kp.pilih-dosbing") }}">
        {{ csrf_field() }}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Pilih Dosen Pembimbing</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" value="{{ $pengajuanKp->id }}">
                    <select name="nip" class="form-control">
                        <option value="">-- Dosen Pembimbing --</option>
                        @foreach($dosen as $value)
                        <option value="{{ $value->nip }}">{{ $value->kode_prodi }} - {{ $value->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </div>
        </div>
    </div>
    </form>
@endsection

resources/views/kaprodi/pengajuan-kp/index.blade.php
@extends('layouts.app')

@section('content')

    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <div class="row mt-3">
        <div class="col-md-12">
            <div class="card shadow-sm mb-4">
                <div class="card-body table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">ID Pengajuan</th>
                                <th scope="col">Judul</th>
                                <th scope="col">Tanggal Pengajuan</th>
                                <th scope="col">Status Pengajuan</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($pengajuanKP as $value)
                                <tr>
                                    <th scope="row">{{ $value->id }}</th>
                                    <td>{{ $value->judul }}</td>
                                    <td>{{ $value->created_at }}</td>
                                    <td><span class="badge badge-warning">{{ $value->status }}</span></td>
                                    <td>
                                        <a href="{{ route("kaprodi.pengajuan.kp.detail", ["id" => $value->id]) }}" class="btn btn-sm btn-outline-primary"> Detail</a>
                                        <a href="" class="btn btn-sm btn-primary"> Edit</a>
                                    </td>
                                </tr>
                                <tr>
                                    <th colspan="2"> Dosen : {{ $value->nip }}</th>
                                    <td colspan="2">Masa Belaku : {{ $value->created_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>


                </div>
            </div>
        </div>
    </div>

@endsection