routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

// User
Route::group(["prefix" => "user", "as" => "user."], function (){
   Route::get("/mahasiswa-register", "UserController@mahasiswaRegister")->name("mahasiswa.register");
   Route::post("/mahasiswa-register", "UserController@postMahasiswaRegister")->name("post.mahasiswa.register");
   Route::get("/login", "UserController@login")->name("login");
   Route::post("/login", "UserController@postLogin")->name("post.login");
   Route::get("/logout", "UserController@logout")->name("logout");
});

// Admin
Route::group(["prefix" => "admin", "as" => "admin.", "namespace" => "Admin", "middleware" => "admin"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //admin mahasiswa
    Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa."], function (){
        Route::get("/", "MahasiswaController@index")->name("index");
        Route::get("/tambah", "MahasiswaController@tambah")->name("tambah");
        Route::post("/tambah", "MahasiswaController@postTambah")->name("post.tambah");
    });
    //admin dosen
    Route::group(["prefix" => "dosen", "as" => "dosen."], function (){
        Route::get("/", "DosenController@index")->name("index");
        Route::get("/tambah", "DosenController@tambah")->name("tambah");
        Route::post("/tambah", "DosenController@postTambah")->name("post.tambah");
        Route::get("/buat-akun-dosen/{nip}", "DosenController@buatAkunDosen")->name("buat-akun-dosen");
        Route::post("/buat-akun-dosen/{nip}", "DosenController@postBuatAkunDosen")->name("post.buat-akun-dosen");
    });
    //sks
    Route::group(["prefix" => "sks", "as" => "sks."], function (){
        Route::get("/", "SKSController@index")->name("index");
        Route::post("/import-excel", "SKSController@importExcel")->name("post.import.excel");
    });
});

// Mahasiswa
Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa.","namespace" => "Mahasiswa", "middleware" => "mahasiswa"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pembayaran
    Route::group(["prefix" => "pembayaran", "as" => "pembayaran."], function (){
        Route::get("/bayar", "PembayaranController@bayar")->name("bayar");
        Route::post("/bayar", "PembayaranController@postBayar")->name("post.bayar");
    });
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/pengajuan", "PengajuanKPController@pengajuan")->name("pengajuan");
        Route::post("/pengajuan", "PengajuanKPController@postPengajuan")->name("post.pengajuan");
    });
});

// Kaprodi
Route::group(["prefix" => "kaprodi", "as" => "kaprodi.", "namespace" => "Kaprodi"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/detail/{id}", "PengajuanKPController@detail")->name("detail");
        Route::get("/terima/{id}", "PengajuanKPController@terima")->name("terima");
        Route::post("/pilih-dosbing", "PengajuanKPController@pilihDosbing")->name("pilih-dosbing");
    });
});

// Dosen
Route::group(["prefix" => "dosen", "as" => "dosen.", "namespace" => "Dosen"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");

});

app/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Mail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    // declare guard type
    protected $guard = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'mahasiswa_id', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\UserException;
use App\Http\Requests\UserLoginRequest;
use App\Http\Requests\UserRegisterRequest;
use App\Service\Impl\SessionServiceImpl;
use App\Service\Impl\UserServiceImpl;
use App\Service\SessionService;
use App\Service\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
    private UserService $userService;
    private SessionService $sessionService;

    public function __construct()
    {
        $this->userService = new UserServiceImpl();
        $this->sessionService = new SessionServiceImpl();
    }

    public function mahasiswaRegister()
    {
        return view("user/mahasiswa-register");
    }

    public function postMahasiswaRegister(UserRegisterRequest $request)
    {
        try {
            $response = $this->userService->mahasiswaRegister($request);

            return redirect()->route("user.login")
                ->with("success", "Berhasil mendaftar akun sikapta, silahkan login");
        }catch (UserException $exception){
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }
    }

    public function login()
    {
        return view("user.login");
    }

    public function postLogin(UserLoginRequest $request)
    {
        try {
            $response = $this->userService->login($request);
            $this->sessionService->create($response->user->id);

            if ($response->user->role == "mahasiswa") { // mahasiswa
                return redirect()->route("mahasiswa.dashboard")
                    ->with("success", "Berhasil login");
            }else if ($response->user->role == "dosen"){ // dosen
                return redirect()->route("dosen.dashboard")
                    ->with("success", "Berhasil login");
            }else if ($response->user->role == "kaprodi"){ // kaprodi
                return redirect()->route("kaprodi.dashboard")
                    ->with("success", "Berhasil login");
            }else if ($response->user->role == "admin"){ // admin
                return redirect()->route("admin.dashboard")
                    ->with("success", "Berhasil login");
            } else{
                return back()->with("error", "Gagal Login")->withInput($request->all());
            }
        }catch (UserException $exception) {
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }
    }

    public function logout()
    {
        $this->sessionService->destroy();
        return redirect()->route("user.login");
    }

}

resources/views/user/home.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-2">
    <div class="col-12">
        <p>Dashborad</p>
        <h4>Selamat Datang, {{ Auth::user()->mahasiswa->nama }}</h4>
        <hr>
    </div>
</div>

<!--Top-->
<div class="row">
<!-- Task -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Progress
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                        style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 mb-4">
        <div class="card shadow mb-2">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Profile</h6>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="120" height="120">
                </div>
                <p class="mb-4">
                    <div class="row">
                        <div class="col">
                            NAMA
                        </div>
                        <div class="col-7">
                            {{ Auth::user()->mahasiswa->nama }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            SKS LULUS
                        </div>
                        <div class="col-7">
                            140
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            Tagihan
                        </div>
                        <div class="col-7">
                            <b>Terbayar</b>
                        </div>
                    </div>
                </p>
                
                <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Memenuhi Syarat
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-danger"></i> Belum Memenuhi
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-8 mb-4">
        <div class="card shadow mb-2">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">ALUR SIKAPTA</h6>
            </div>
            <div class="card-body">
                <p>
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        Kerja Praktek</div>
                </p>
                <p class="mb-4">
                    <div class="row">
                        <div class="col-auto">
                            1
                        </div>
                        <div class="col-11">
                            Mahasiswa telah lulus matakuliah
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-auto">
                            2
                        </div>
                        <div class="col-11">
                            Mahasiswa telah lulus matakuliah
                        </div>
                    </div>
                </p>
                
                <p>
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        Tugas Akhir</div>
                </p>

                <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Memenuhi Syarat
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-danger"></i> Belum Memenuhi
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row mt-2">
    <div class="col-sm-3 col-sm-6 mt-3">
        <a href="{{ route('persyaratan') }}" class="btn">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <img src="{{ asset('icon/svg/accept.svg') }}" alt="" class="img-fluid" width="100">
                        </div>
                        <div class="col-6 d-flex-row ">
                        <h4 class="text-left font-weight-bold text-primary">Alur Pengajuan KP dan TA</h4>
                            <p class="text-left">With supporting text below as a natural lead-in to additional content.</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-sm-3 col-sm-6 mt-3">
        <a href="{{ route('pengajuanKP.formPengajuan') }}" class="btn">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <img src="{{ asset('icon/svg/creative-idea.svg') }}" alt="" class="img-fluid" width="100">
                        </div>
                        <div class="col-6 d-flex-row ">
                        <h4 class="text-left font-weight-bold text-primary">Kerja Praktek</h4>
                            <p class="text-left">With supporting text below as a natural lead-in to additional content.</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-sm-3 col-sm-6 mt-3">
        <a href="{{ route('bimbingan.mahasiswa') }}" class="btn">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <img src="{{ asset('icon/svg/calendar.svg') }}" alt="" class="img-fluid" width="100">
                        </div>
                        <div class="col-6 d-flex-row ">
                        <h4 class="text-left font-weight-bold text-primary">Bimbingan</h4>
                            <p class="text-left">With supporting text below as a natural lead-in to additional content.</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-sm-3 col-sm-6 mt-3">
        <a href="{{route('pengajuanTA.formPengajuan')}}" class="btn">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <img src="{{ asset('icon/svg/database.svg') }}" alt="" class="img-fluid" width="100">
                        </div>
                        <div class="col-6 d-flex-row ">
                        <h4 class="text-left font-weight-bold text-primary">Tugas Akhir</h4>
                            <p class="text-left">With supporting text below as a natural lead-in to additional content.</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>
@endsection

resources/views/user/homeElse.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row mt-4">
        <div class="col-md-12">

        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Mohon Maaf</h4>
            <p>anda belum memenuhi syarat untuk mengajukan Kerja Praktek atau Tugas Akhir , silahkan cek cek kembali <a href="{{ route('pengajuanKP.formPengajuan') }}"> syarat-syarat dan ketentuan.</a></p>
            <hr>
            <p class="mb-0">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae illum rem minus deserunt totam eveniet ipsum quaerat voluptate corporis recusandae impedit doloribus, veniam, natus tempora voluptas inventore expedita aut ea?</p>
        </div>

        </div>
    </div>
</div>
@endsection

resources/views/user/login.blade.php
@extends('layouts.auth')
<style>
    .form-control-user {
        padding: 0 1rem !important;
        height: 3rem !important;
    }
</style>
@section('content')
<div class="row justify-content-center">
    <div class="col-lg-9">
        <div class="p-5">
            <div class="text-center">
                <img src="{{ asset('img/sikapta-logo.png') }}" alt="" class="img-fluids" width="150">
                <h1 class="h4 text-gray-900 my-4">Selamat Datang di Sikapta Unsiq</h1>
            </div>
            {{--error message--}}
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            <form class="user" method="POST" action="{{ route('user.login') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    
                        <input id="email" type="text" placeholder="Masukan Alamat Email" class="form-control form-control-user" name="email" value="{{ old('email') }}" autofocus autocomplete="off">

                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong class="text-danger ml-3 mt-2">{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                 
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    
                        <input id="password" type="password" placeholder="Password" class="form-control form-control-user" name="password">

                        @if ($errors->has('password'))
                            <span class="help-block">
                                <strong class="text-danger ml-3">{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                
                </div>
{{--                <div class="form-group">--}}
{{--                    <select name="role" class="form-control form-control-user">--}}
{{--                        <option value="mahasiswa">Mahasiswa</option>--}}
{{--                        <option value="dosen">Dosen</option>--}}
{{--                        <option value="admin">Admin</option>--}}
{{--                    </select>--}}
{{--                </div>--}}
                <button type="submit" class="btn btn-primary btn-user btn-block">
                    Login
                </button>
                
            </form>

            <hr>
            <div class="text-center">
                Jika belum memiliki akun SIKAPTA, silahkan melakukan registrasi akun SIKAPTA.
                <a class="link" href="{{ route('user.mahasiswa.register') }}"> Daftar di sini.</a>
            </div>
        </div>
    </div>
@endsection

resources/views/user/mahasiswa-register.blade.php
@extends('layouts.auth')

@section('content')
    <div class="col-lg-9">
        <div class="p-5">
            <div class="text-center">
                <img src="{{ asset('img/sikapta-logo.png') }}" alt="" class="img-fluids" width="150">
                <h1 class="h4 text-gray-900 my-4">Registrasi Akun Sikapta Unsiq</h1>
            </div>
            {{--error message--}}
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            <form class="user" method="POST" action="{{ route('user.post.mahasiswa.register') }}">
                {{ csrf_field() }}

                <div class="form-group">

                    <input id="nim" type="nim" placeholder="Nomor Induk Mahasiswa" class="form-control form-control-user {{ $errors->has('nim') ? ' has-error' : '' }}" name="nim" value="{{ old('nim') }}" autofocus>

                    @if ($errors->has('nim'))
                        <span class="help-block">
                            <strong class="text-danger ml-3 mt-2">{{ $errors->first('nim') }}</strong>
                        </span>
                    @endif

                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">

                    <input id="email" type="email" placeholder="Email" class="form-control form-control-user" name="email" value="{{ old('email') }}" autofocus>

                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong class="text-danger ml-3 mt-2">{{ $errors->first('email') }}</strong>
                        </span>
                    @endif

                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">

                    <input id="password" type="password" placeholder="Password" class="form-control form-control-user" name="password">

                    @if ($errors->has('password'))
                        <span class="help-block">
                        <strong class="text-danger ml-3">{{ $errors->first('password') }}</strong>
                    </span>
                    @endif

                </div>
                <div class="form-group{{ $errors->has('password-confirm') ? ' has-error' : '' }}">
                    <input id="password-confirm" type="password" placeholder="Password Confirmation" class="form-control form-control-user" name="password_confirmation">
                </div>


                <button type="submit" class="btn btn-primary btn-user btn-block">
                    Daftar Akun
                </button>

            </form>

            <div class="text-center">
                Sudah punya akun?
                <a class="link mt-3" href="{{ route("user.login") }}"> Login di sini.</a>
            </div>
        </div>
    </div>


@endsection

resources/views/user/persyaratan.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-3">
    <div class="col-12">
        <h4>Persyaratan Kerja Praktek</h4>
        <hr>
    </div>
</div>

<div class="row mt-3">
    <div class="col-12">
        <div class="card">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Pengajuan Kerja Praktek</h6>
        </div>
            <div class="row">
                
            </div>
        </div>
    </div>
</div>

@endsection