routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

// User
Route::group(["prefix" => "user", "as" => "user."], function (){
   Route::get("/mahasiswa-register", "UserController@mahasiswaRegister")->name("mahasiswa.register");
   Route::post("/mahasiswa-register", "UserController@postMahasiswaRegister")->name("post.mahasiswa.register");
   Route::get("/login", "UserController@login")->name("login");
   Route::post("/login", "UserController@postLogin")->name("post.login");
   Route::get("/logout", "UserController@logout")->name("logout");
});

// Admin
Route::group(["prefix" => "admin", "as" => "admin.", "namespace" => "Admin", "middleware" => "admin"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //admin mahasiswa
    Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa."], function (){
        Route::get("/", "MahasiswaController@index")->name("index");
        Route::get("/tambah", "MahasiswaController@tambah")->name("tambah");
        Route::post("/tambah", "MahasiswaController@postTambah")->name("post.tambah");
    });
    //admin dosen
    Route::group(["prefix" => "dosen", "as" => "dosen."], function (){
        Route::get("/", "DosenController@index")->name("index");
        Route::get("/tambah", "DosenController@tambah")->name("tambah");
        Route::post("/tambah", "DosenController@postTambah")->name("post.tambah");
        Route::get("/buat-akun-dosen/{nip}", "DosenController@buatAkunDosen")->name("buat-akun-dosen");
        Route::post("/buat-akun-dosen/{nip}", "DosenController@postBuatAkunDosen")->name("post.buat-akun-dosen");
    });
    //sks
    Route::group(["prefix" => "sks", "as" => "sks."], function (){
        Route::get("/", "SKSController@index")->name("index");
        Route::post("/import-excel", "SKSController@importExcel")->name("post.import.excel");
    });
});

// Mahasiswa
Route::group(["prefix" => "mahasiswa", "as" => "mahasiswa.","namespace" => "Mahasiswa", "middleware" => "mahasiswa"], function (){
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pembayaran
    Route::group(["prefix" => "pembayaran", "as" => "pembayaran."], function (){
        Route::get("/bayar", "PembayaranController@bayar")->name("bayar");
        Route::post("/bayar", "PembayaranController@postBayar")->name("post.bayar");
    });
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/pengajuan", "PengajuanKPController@pengajuan")->name("pengajuan");
        Route::post("/pengajuan", "PengajuanKPController@postPengajuan")->name("post.pengajuan");
    });
});

// Kaprodi
Route::group(["prefix" => "kaprodi", "as" => "kaprodi.", "namespace" => "Kaprodi"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");
    //pengajuan Kp
    Route::group(["prefix" => "pengajuan-kp", "as" => "pengajuan.kp."], function (){
        Route::get("/", "PengajuanKPController@index")->name("index");
        Route::get("/detail/{id}", "PengajuanKPController@detail")->name("detail");
        Route::get("/terima/{id}", "PengajuanKPController@terima")->name("terima");
        Route::post("/pilih-dosbing", "PengajuanKPController@pilihDosbing")->name("pilih-dosbing");
    });
});

// Dosen
Route::group(["prefix" => "dosen", "as" => "dosen.", "namespace" => "Dosen"], function (){
    //
    Route::get("/dashboard", "HomeController@dashboard")->name("dashboard");

});

app/Mahasiswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Symfony\Component\HttpKernel\Profiler\Profile;

class Mahasiswa extends Model
{
    //
    protected $fillable = [
        'nim',
        'nama',
        'no_hp',
        'prodi',
        'status'
    ];

    public function pengajuan()
    {
        return $this->hasOne(Profile::class);
    }
    public function prodi()
    {
        return $this->belongsTo(Prodi::class);
    }
    public function user()
    {
        return $this->hasOne(User::class);
    }
}

app/Http/Controllers/Admin/MahasiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exceptions\DosenException;
use App\Exceptions\MahasiswaException;
use App\Exceptions\UserException;
use App\Http\Requests\MahasiswaTambahRequest;
use App\Model\Mahasiswa;
use App\Model\Prodi;
use App\Service\Impl\MahasiswaServiceImpl;
use App\Service\MahasiswaService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MahasiswaController extends Controller
{
    //

    private MahasiswaService $mahasiswaService;

    public function __construct()
    {
        $this->mahasiswaService = new MahasiswaServiceImpl();
    }


    public function index(Request $request)
    {
        $prodi = Prodi::all();
        $mahasiswa = Mahasiswa::paginate();


        return view("admin.mahasiswa.index", [
            "title" => "Mahasiswa",
            "prodi" => $prodi,
            "mahasiswa" => $mahasiswa
        ]);
    }

    public function tambah()
    {
        $prodi = Prodi::all();
        return view("admin.mahasiswa.tambah", [
            "title" => "Tambah Data Mahasiswa",
            "prodi" => $prodi
        ]);
    }

    public function postTambah(MahasiswaTambahRequest $request)
    {
        try {
            $response = $this->mahasiswaService->tambah($request);
            return redirect()->route("admin.mahasiswa.index")->with("success", "Berhasil menmbah mahasiswa" . $response->mahasiswa->nama);
        }catch (MahasiswaException $exception){
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }
    }
}

app/Http/Controllers/Mahasiswa/HomeController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Service\Impl\SessionServiceImpl;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    private SessionService $sessionService;

    public function __construct()
    {
        $this->sessionService = new SessionServiceImpl();
    }


    public function dashboard()
    {
        $mahasiswa = $this->sessionService->currentMahasiswa();
        return view("mahasiswa.dashboard", [
            "title" => "Dashboard",
            "mahasiswa" => $mahasiswa
        ]);
    }
}

app/Http/Controllers/Mahasiswa/PembayaranController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Exceptions\PembayaranException;
use App\Http\Requests\PembayaranRequest;
use App\Service\Impl\PembayaranServiceImpl;
use App\Service\PembayaranService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PembayaranController extends Controller
{
    private PembayaranService $pembayaranService;

    public function __construct()
    {
        $this->pembayaranService = new PembayaranServiceImpl();
    }

    public function bayar()
    {
        return view("mahasiswa.pembayaran.bayar", [
            "title" => "Pembayaran Pengajuan"
        ]);
    }
    public function postBayar(PembayaranRequest $request)
    {
        try {
            $response = $this->pembayaranService->bayar($request);
            return back()->with("success", "Berhasil membayar pengajuan " . $response->pembayaran->jenis_pengajuan);
        }catch (PembayaranException $exception){
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }

    }

}

app/Http/Controllers/Mahasiswa/PengajuanKPController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Exceptions\PengajuanKPException;
use App\Http\Requests\PengajuanKPRequest;
use App\Model\PengajuanKP;
use App\Service\Impl\PengajuanKPServiceImpl;
use App\Service\Impl\SessionServiceImpl;
use App\Service\PengajuanKPService;
use App\Service\SessionService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PengajuanKPController extends Controller
{
    //

    private PengajuanKPService $pengajuanKPService;
    private SessionService $sessionService;

    public function __construct()
    {
        $this->pengajuanKPService = new PengajuanKPServiceImpl();
        $this->sessionService = new SessionServiceImpl();
    }


    public function index()
    {
        $pengajuanKP = PengajuanKP::where("nim", $this->sessionService->currentMahasiswa()->nim)
            ->get();

        return view("mahasiswa.pengajuan-kp.index", [
            "title" => "Pengajuan Kerja Praktek",
            "pengajuanKP" => $pengajuanKP
        ]);
    }

    public function pengajuan()
    {
        $mahasiswa = $this->sessionService->currentMahasiswa();
        return view("mahasiswa.pengajuan-kp.pengajuan", [
            "title" => "Form Pengajuan Kerja Praktek",
            "mahasiswa" => $mahasiswa
        ]);
    }

    public function postPengajuan(PengajuanKPRequest $request)
    {
        try {
            $response = $this->pengajuanKPService->pengajuan($request);
            return redirect()->route("mahasiswa.pengajuan.kp.index")->with("success", "Berhasil melakukan pengajuan Kerja Praktek");
        }catch (PengajuanKPException $exception){
            return back()->with("error", $exception->getMessage())->withInput($request->all());
        }
    }
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use DB;
use App\Mahasiswa;

class MahasiswaController extends Controller
{
    public function index()
    {
        return view('user.mahasiswa');
    }

    public function getPosts()
    {
    	$mhs = DB::table('mahasiswa')->select('*');
        return Datatables::of($mhs)
            ->make(true);
    }
}

resources/views/admin/mahasiswa/index.blade.php
@extends('layouts.admin')

@section('content')

    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <!-- DataTales Example -->
    <div class="card shadow-sm mt-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Mahasiswa</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <form method="get" action="{{ route("admin.mahasiswa.index") }}">
                        <div class="form-group row">
                            <label for="prodi" class="col-md-2 col-form-label">Prodi</label>
                            <div class="col-md-5">
                                <select name="prodi" class="form-control" id="prodi">
                                    @foreach($prodi as $value)
                                        <option value="{{ $value->kode_prodi }}">{{ $value->kode_prodi }} - {{ $value->prodi }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <button class="btn mb-2 btn-success btn-sm col-form-label">Submit</button>
                    </form>
                </div>
                <div class="col-md-6">
                    <button type="button" class="btn float-right btn-sm btn-outline-success mx-2" data-toggle="modal" data-target="#impotrModal">
                        Import Excel
                    </button>
                    <a href="" class="btn btn-success btn-sm float-right mx-2">Export Excel</a>
                    <a href="{{ route("admin.mahasiswa.tambah") }}" class="btn btn-primary btn-sm float-right mx-2">Tambah Data</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>NIM</th>
                        <th>Prodi</th>
                        <th>Nomer Handphone</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $nomer = 1 ?>
                    @foreach($mahasiswa as $value)

                    <tr>
                        <td>{{ $nomer }}</td>
                        <td>{{ $value->nama }}</td>
                        <td>{{ $value->nim }}</td>
                        <td>{{ $value->prodi->prodi }}</td>
                        <td>{{ $value->nomer_hp }}</td>
                        <td><a class="btn btn-sucess"></a></td>
                    </tr>
                    <?php $nomer++ ?>
                    @endforeach

                    </tbody>
                </table>
                {{ $mahasiswa->render() }}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/mahasiswa/tambah.blade.php
@extends('layouts.admin')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br>
            @endforeach
        </div>
    @endif
    @if(session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif
    <div class="row mt-3">
        <div class="col-md-10">
            <div class="card shadow-sm mb-4">
                <div class="card-header py-3">
                    <a href="{{ route("admin.mahasiswa.index") }}" class="btn btn-sm btn-success">Kembalii</a>
                </div>
                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('admin.mahasiswa.post.tambah') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="nim" class="font-weight-bold">Nomer Induk Mahasiswa</label>
                            <input type="text" name="nim" class="form-control" value="{{ old("nim") }}" placeholder="Nomer Induk Mahasiswa">
                        </div>

                        <div class="form-group">
                            <label for="nama"  class="font-weight-bold">Nama</label>
                            <input type="text" name="nama" class="form-control" value="{{ old("nama") }}" placeholder="Nama">
                        </div>

                        <div class="form-group">
                            <label for="prodi" class="font-weight-bold">Prodi</label>
                            <select name="prodi" class="form-control" id="prodi">
                                @foreach($prodi as $value)
                                    <option value="{{ $value->kode_prodi }}">{{ $value->kode_prodi }} - {{ $value->prodi }}</option>
                                @endforeach
                            </select>
                        </div>

                        <button class="btn btn-sm btn-primary">Tambah</button>

                    </form>
                </div>
            </div>
        </div>

@endsection